#!/usr/bin/env python3
from pathlib import Path


def main():
    root = Path(__file__).resolve().parents[1]
    out_path = root / "lib" / "Txt" / "GbkUnicodeTable.generated.h"

    pairs = []
    for lead in range(0x81, 0xFF):
        for trail in range(0x40, 0xFF):
            if trail == 0x7F:
                continue
            raw = bytes((lead, trail))
            try:
                text = raw.decode("gbk")
            except UnicodeDecodeError:
                continue
            if len(text) != 1:
                continue
            cp = ord(text)
            if cp <= 0x7F or cp > 0xFFFF:
                continue
            pairs.append(((lead << 8) | trail, cp))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by scripts/gen_gbk_table.py. Do not edit manually.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstddef>\n")
        f.write("#include <cstdint>\n\n")
        f.write("struct GbkUnicodePair {\n")
        f.write("  uint16_t gbk;\n")
        f.write("  uint16_t unicode;\n")
        f.write("};\n\n")
        f.write(f"static constexpr GbkUnicodePair GBK_UNICODE_TABLE[{len(pairs)}] = {{\n")
        for gbk, cp in pairs:
            f.write(f"    {{0x{gbk:04X}, 0x{cp:04X}}},\n")
        f.write("};\n\n")
        f.write(f"static constexpr size_t GBK_UNICODE_TABLE_SIZE = {len(pairs)};\n")

    print(f"Generated {out_path} ({len(pairs)} entries)")


if __name__ == "__main__":
    main()
